# Generated by Django 5.2.8 on 2025-11-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_activity_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Activity',
        ),
    ]
